# Generated by Django 3.2.8 on 2021-10-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AllocationWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title']},
        ),
    ]
