# Generated by Django 3.2.8 on 2021-11-23 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AllocationWebApp', '0004_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
